name: React CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build the project
      - name: Build the project
        run: npm run build

      # 5. Test the application
      - name: Test the application
        run: |
          npm install -g serve
          sudo apt-get update && sudo apt-get install -y curl
          serve -s build -l 3000  | grep -q "Hello world! - Haya Aouate"; then
              echo "Test passed!"
              break
          fi
          sleep 10
          STATUS=$(curl -o /dev/null -s -w "%{http_code}" http://localhost:3000)
          if [ $STATUS -ne 200 ]; then
            echo "Server did not return HTTP 200 OK"
            exit 1
          fi

      # 6. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
